handle RuntimeError due to constraint violation while sampling from priors (#1451)
Summary:
Pull Request resolved: https://github.com/pytorch/botorch/pull/1451

On fitting retries, sometimes sampling from the prior will violate a parameter constraint, leading an error like
> RuntimeError: Attempting to manually set a parameter value that is out of bounds of its current constraints...

Reviewed By: dme65, saitcakmak

Differential Revision: D40272361

fbshipit-source-id: c075e4e45339a9b9e5675ea2951c16ba5d603ea2