Fix minimize test due to issue with rounding np array element (#1765)
Summary:
When running tests locally I ran into the following error:

self = <test.optim.utils.test_timeout.TestMinimizeWithTimeout testMethod=test_minimize_with_timeout>

    def test_minimize_with_timeout(self):
        def f_and_g(x: np.ndarray, sleep_sec: float = 0.0):
            time.sleep(sleep_sec)
            return x**2, 2 * x

        base_kwargs = {
            "fun": f_and_g,
            "x0": np.array([1.0]),
            "method": "L-BFGS-B",
            "jac": True,
            "bounds": [(-2.0, 2.0)],
        }

        with self.subTest("test w/o timeout"):
            res = minimize_with_timeout(**base_kwargs)
            self.assertTrue(res.success)
            self.assertAlmostEqual(res.fun, 0.0)
            self.assertAlmostEqual(res.x, 0.0)
            TypeError: type numpy.ndarray doesn't define __round__ method

This adds an `item()` to the single-element arrays to return a python `float` instead. Not sure why this doesn't fail in the CI, presumably it's a scipy/numpy versioning issue? Probably not worth digging deep here if this works both locally and on the CI.

Pull Request resolved: https://github.com/pytorch/botorch/pull/1765

Reviewed By: esantorella

Differential Revision: D44405834

Pulled By: Balandat

fbshipit-source-id: 980da080dcc33f10f482261dce4990a65798229e